/**
 * Firestore Security Rules Test Specification (Dirty Dozen Verification)
 * Verifies all 12 adversarial payloads against /characters/{characterId}
 */

export const DIRTY_DOZEN_TEST_CASES = [
  {
    id: 1,
    name: 'Unauthenticated Create',
    auth: null,
    operation: 'create',
    path: '/characters/char_1',
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 2,
    name: 'Unverified Email Create',
    auth: { uid: 'user_a', email_verified: false },
    operation: 'create',
    path: '/characters/char_1',
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 3,
    name: 'Identity Spoofing on Create (ownerId != auth.uid)',
    auth: { uid: 'user_a', email_verified: true },
    operation: 'create',
    path: '/characters/char_1',
    payloadOverride: { ownerId: 'user_b' },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 4,
    name: 'Shadow Field Injection on Create',
    auth: { uid: 'user_a', email_verified: true },
    operation: 'create',
    path: '/characters/char_1',
    payloadOverride: { isAdmin: true },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 5,
    name: 'ID Poisoning (invalid characters in doc ID)',
    auth: { uid: 'user_a', email_verified: true },
    operation: 'create',
    path: '/characters/invalid$id!',
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 6,
    name: 'Client Timestamp Forgery on Create',
    auth: { uid: 'user_a', email_verified: true },
    operation: 'create',
    path: '/characters/char_1',
    payloadOverride: { createdAt: '1999-01-01T00:00:00Z' },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 7,
    name: 'Unauthorized Read (get by non-owner)',
    auth: { uid: 'user_b', email_verified: true },
    operation: 'get',
    path: '/characters/char_owned_by_a',
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 8,
    name: 'Blanket List Query without ownerId filter',
    auth: { uid: 'user_b', email_verified: true },
    operation: 'list',
    path: '/characters',
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 9,
    name: 'Owner Hijack on Update',
    auth: { uid: 'user_a', email_verified: true },
    operation: 'update',
    path: '/characters/char_owned_by_a',
    payloadOverride: { ownerId: 'user_b' },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 10,
    name: 'Immutable createdAt Mutation on Update',
    auth: { uid: 'user_a', email_verified: true },
    operation: 'update',
    path: '/characters/char_owned_by_a',
    payloadOverride: { createdAt: '2026-10-04T00:00:00Z' },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 11,
    name: 'Value Poisoning on Update (oversized fullNameAndAlias)',
    auth: { uid: 'user_a', email_verified: true },
    operation: 'update',
    path: '/characters/char_owned_by_a',
    payloadOverride: { fullNameAndAlias: 'X'.repeat(500) },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 12,
    name: 'Unauthorized Delete by non-owner',
    auth: { uid: 'user_b', email_verified: true },
    operation: 'delete',
    path: '/characters/char_owned_by_a',
    expected: 'PERMISSION_DENIED',
  },
];
